# Generated by Django 2.1.5 on 2019-01-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_cpu_networkdevice_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='asset',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-c_time', '-m_time'], 'verbose_name': '资产总表', 'verbose_name_plural': '资产总表'},
        ),
        migrations.AddField(
            model_name='server',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存大小(GB)'),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_core_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='CPU核数'),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='物理CPU个数'),
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
    ]
