# Generated by Django 2.1.5 on 2019-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_auto_20190117_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='storage_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='设备名'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, 'CAS'), (1, 'UIS'), (2, 'CloudOs'), (3, 'CloudClass'), (4, '普通windows服务器'), (3, '普通linux服务器')], default=0, verbose_name='服务器类型'),
        ),
    ]
