# Generated by Django 2.1.5 on 2019-01-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_storagedevice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, '云计算'), (1, '网络'), (2, '安全'), (3, '其他')], default=0, verbose_name='产品线'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '故障'), (3, '请勿删除或重装')], default=0, verbose_name='设备状态'),
        ),
    ]
