# Generated by Django 2.1.5 on 2019-01-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_auto_20190117_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, '云计算'), (1, '网络'), (2, '安全'), (3, '其他')], default=0, verbose_name='所属产品线'),
        ),
    ]
