# Generated by Django 2.1.5 on 2019-01-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_auto_20190121_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, 'CAS'), (1, 'UIS'), (2, 'CloudOs'), (3, 'CloudClass'), (4, 'UIS企业版'), (5, '其它')], default=0, verbose_name='服务器类型'),
        ),
    ]
