# Generated by Django 2.1.5 on 2019-02-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_auto_20190128_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '故障')], default=0, verbose_name='设备状态'),
        ),
    ]
